### ISSUE TITLE
Context: This is the inherited member.   void get initState

### ISSUE THREAD

**Issue by fahjan** [KarimMohamed20/SplashScreenFlutterPackage#25]
Compiler message:
file:///D:/androidstudiolib/flutter/.pub-cache/hosted/pub.dartlang.org/splashscreen-1.2.0/lib/splashscreen.dart:47:8: Error: Can't declare a member that conflicts with an inherited one.
  void initState() {
       ^^^^^^^^^
file:///D:/androidstudiolib/flutter/packages/flutter/lib/src/widgets/framework.dart:1007:12: Context: This is the inherited member.
  void get initState {
           ^^^^^^^^^
file:///D:/androidstudiolib/flutter/.pub-cache/hosted/pub.dartlang.org/splashscreen-1.2.0/lib/splashscreen.dart:48:11: Error: This expression has type 'void' and can't be used.
    super.initState();
          ^
file:///D:/androidstudiolib/flutter/.pub-cache/hosted/pub.dartlang.org/splashscreen-1.2.0/lib/splashscreen.dart:48:20: Error: The method 'call' isn't defined for the class 'void'.
Try correcting the name to the name of an existing method, or defining a method named 'call'.
    super.initState();

![image](https://user-images.githubusercontent.com/2186011/54215016-e0bf0b80-44ef-11e9-846c-5f0f4d1a1c77.png)

**Comment by ahmedmgh67** [comment]
how to reproduce the issue?

**Comment by fahjan** [comment]
reinstall flutter solve this issue :) 
thank you ...
