### ISSUE TITLE
Navigate to Multiple pages after navigateAfterSeconds

### ISSUE THREAD

**Issue by Mallikarjun-0369** [KarimMohamed20/SplashScreenFlutterPackage#26]
In My Case i want to navigate to different pages based on some login response like below, like below.

   _handleNavigation() {
    if(UserSession.loginStatus == 0) {
      print('LoginStatus -> ${UserSession.isLoggedIn}');
      return LoginPage();
    } else {
      print('LoginStatus -> ${UserSession.isLoggedIn}');
      switch (UserSession.shortName) {
        case 'stay':
          return AccommodationListPage();
//          break;

        case 'activity':
          return ActivityDashboard();
//          break;

        case 'transport':
          return TransportDashboard();
//          break;

        case 'tour':
          return PendingContractsPage();
      }
    }
  }

But am getting issues with this function: Like it "Should be String or Widget."
How can i achieve my requirement. Please help me out on this.
Thanks Alot !.

**Comment by Hemedy** [comment]
Same Error

**Comment by ahmedmgh67** [comment]
This issue will be solved if you added the return type of Widget to the function like this
```dart
Widget _handleNavigation() {
return WhateverPage();
}

```
Thank you
