### ISSUE TITLE
How I set an asset image as background?

### ISSUE THREAD

**Issue by mhsampaio** [KarimMohamed20/SplashScreenFlutterPackage#28]
class _WelcomePageState extends State<WelcomePage> {
  @override
  Widget build(BuildContext context) {
    return SplashScreen(
                seconds: 25,
                navigateAfterSeconds: HomePage(),
                title: Text('Ace Squad',
                    style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 30.0
                    ),),
                image: Image.asset("images/skull.png",
                    height: 250.0,
                    width: 250.0
                ),
                **imageBackground: ,**
                //backgroundColor: Colors.black,
                styleTextUnderTheLoader: TextStyle(),
                photoSize: 100.0,
                onClick: ()=>print("Flutter Egypt"),
                loaderColor: Colors.white           
    );
  }
}

**Comment by cadrogui** [comment]
same question here...

**Comment by KarimMohamed2005** [comment]
Sorry for everyone stayed longtime with issues I was busy but now I will work on it until i fix all issues and publish a new release thx for anyone.

**Comment by SonQBChau** [comment]
This has been answered #19, you can use backgroundImage property

**Comment by juaniyyo** [comment]
@mhsampaio, this is my solution:
![Captura de pantalla 2019-09-17 a las 17 42 49](https://user-images.githubusercontent.com/8833186/65057328-bb193000-d972-11e9-9734-b1b43a15037d.png)
And result:
![Captura de pantalla 2019-09-17 a las 17 39 43](https://user-images.githubusercontent.com/8833186/65057375-d1bf8700-d972-11e9-9a11-75edbe08c42e.png)
