### ISSUE TITLE
Add Contributors through bot

### ISSUE THREAD

**Issue by KarimMohamed20** [KarimMohamed20/SplashScreenFlutterPackage#31]

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @ahmedmgh67 for contributor

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @zjinys for contributor

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @ahmedmgh67  for :book:

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @zjinys for ￼:book:

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @jakebolam for infrastructure, tests and code

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @ahmedmgh67 for infrastructure, tests and code

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @zjinys for code

**Comment by KarimMohamed2005** [comment]
@all-contributors please add @play0sm for code

**Comment by ahmedmgh67** [comment]
should we close this issue now?
@KarimMohamed2005
