### ISSUE TITLE
navigateAfterFuture

### ISSUE THREAD

**Issue by sopedro** [KarimMohamed20/SplashScreenFlutterPackage#39]
navigateAfterFuture doesn't exists

**Comment by brazilianbytes** [comment]
You are right @sopedro. This feature was removed since 1b26aac002bf97bc67b0955fcf93c7e9b64ba6d0 commit. I asked to @KarimMohamed2005 to review this commit because the code was removed by mistake (git merge without pull).

**Comment by CoolONEOfficial** [comment]
Temporary solution:
`  splashscreen:
    git:
      url: https://github.com/KarimMohamed2005/SplashScreenFlutterPackage.git
      ref: f8c1ae4f88258bbf33f4c71d1e7bed089da0d65f`

**Comment by kuromukira** [comment]
Has anyone tried implementing this with bloc pattern? By the way, the code was not fixed yet for navigateAfterFuture.

**Comment by IoanaAlexandru** [comment]
Any news on this?

**Comment by kuromukira** [comment]
hi @IoanaAlexandru , you can try using [this](https://github.com/kuromukira/flutter_splash). It's basically the same with this repo, just having the navigateAfterFuture added back.

**Comment by ahmedmgh67** [comment]
Hello guys, 
Karim was so busy these days and he even archived the repo, but he unarchived it today, this repo will be active starting from now. 
This issue has been solved now and will be pushed to the pub.dev package 2 hours from now
Thank you
