### ISSUE TITLE
Little error in example.

### ISSUE THREAD

**Issue by gabofer82** [KarimMohamed20/SplashScreenFlutterPackage#42]
Hi!
In the example page:

https://pub.dev/packages/splashscreen#-example-tab-

code say: 
`**backgroundGradient**: new LinearGradient(colors: [Colors.cyan, Colors.blue], begin: Alignment.topLeft, end: Alignment.bottomRight),`

but must say:
`**gradientBackground**: new LinearGradient(colors: [Colors.cyan, Colors.blue], begin: Alignment.topLeft, end: Alignment.bottomRight),
`

Greetings!

**Comment by ahmedmgh67** [comment]
Done, thanks for contributing
