### ISSUE TITLE
useLoader

### ISSUE THREAD

**Issue by arpavlic03** [KarimMohamed20/SplashScreenFlutterPackage#45]
Hi, I would like to make a PR with a fix for the useLoader attribute, which is a boolean that is later used as a conditional for the buildIndicator/circleprogressloader. How can I contribute to this repo so that other people may be able to use this in their flutter projects?

**Comment by libofeng** [comment]
I am also expecting this feature.

**Comment by ahmedmgh67** [comment]
This has been solved now
Thank you
