### ISSUE TITLE
Implement Custom Loader

### ISSUE THREAD

**Issue by jnvee** [KarimMohamed20/SplashScreenFlutterPackage#47]
**Is your feature request related to a problem? Please describe.**
I was going through this amazing package which was easy to use but one problem was I couldn't implement a Custom Loader because this one is kind of very default and because I wanted to use one of the loaders of the **SpinKit Package.** 

**Describe the solution you'd like to offer.**
I copied the code into my local project and added a new Widget variable and changed the block of code with the default loader in the Expanded Widget. And it worked perfectly.

**Additional context**
![image](https://user-images.githubusercontent.com/53462353/96776309-834aaa80-1406-11eb-838a-c5176537a9ae.png)
![image](https://user-images.githubusercontent.com/53462353/96776565-d290db00-1406-11eb-921e-02efdbcd18ae.png)

**Comment by ahmedmgh67** [comment]
Sorry for being late @jnvee , this idea will be awesome, we'll add in our roadmap for sure, maybe we'll deliver it next month, if you want it faster, you can open a pull request and I'll merge it right away.

**Comment by jnvee** [comment]
great I'll submit a PR in a few hours
